document.addEventListener("DOMContentLoaded", () => {

  const options = document.querySelectorAll(".option input");
  const copy = document.querySelector('.copy-button');
  const quoteInput = document.querySelector(".input-box textarea");
  const generate = document.querySelector(".generate-btn");


  options.forEach((checkbox) => {
      checkbox.addEventListener("click", () => {
        options.forEach((cb) => {
          if (cb !== checkbox && cb.checked) {
            cb.checked = false;
          }
        });
      });
  });

  
  const characters = {
    movie : ["Frankly, my dear, I don't give a damn. - Gone With the Wind, 1939",
      "I'm going to make him an offer he can't refuse. - The Godfather, 1972",
      "You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am. - On the Waterfront, 1954",
      "Toto, I've got a feeling we're not in Kansas anymore. - The Wizard of Oz, 1939",
      "Here's looking at you, kid. - Casablanca, 1942",
      'Go ahead, make my day. - Sudden Impact, 1983',
      "All right, Mr. DeMille, I'm ready for my close-up. - Sunset Boulevard, 1950",
      'May the Force be with you. - Star Wars, 1977',
      "Fasten your seatbelts. It's going to be a bumpy night. - All About Eve, 1950",
      "You talking to me? - Taxi Driver, 1976",
      "What we've got here is failure to communicate. - Cool Hand Luke, 1967",
      'I love the smell of napalm in the morning. - Apocalypse Now, 1979',
      "Love means never having to say you're sorry. - Love Story, 1970",
      'The stuff that dreams are made of. - The Maltese Falcon, 1941',
      'E.T. phone home. -  E.T. The Extra-Terrestrial, 1982',
      "They call me Mister Tibbs! - In the Heat of the Night, 1967",
      'Rosebud. - Citizen Kane, 1941',
      "Made it, Ma! Top of the world! - White Heat, 1949",
      "I'm as mad as hell, and I'm not going to take this anymore! - Network, 1976",
      'Louis, I think this is the beginning of a beautiful friendship. - Casablanca, 1942',
      '\xa0',
      'A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti. - The Silence of the Lambs, 1991',
      'Bond. James Bond. - Dr. No, 1962',
      "There's no place like home. - The Wizard of Oz, 1939",
      "I am big! It's the pictures that got small. - Sunset Blvd., 1950",
      'Show me the money! - Jerry Maguire, 1996',
      "Why don't you come up sometime and see me? - She Done Him Wrong, 1933",
      "I'm walking here! I'm walking here! - Midnight Cowboy, 1969",
      "Play it, Sam. Play 'As Time Goes By.' - Casablanca, 1942",
      "You can't handle the truth! - A Few Good Men, 1992",
      'I want to be alone. - Grand Hotel, 1932',
      'After all, tomorrow is another day! - Gone With the Wind, 1939\xa0',
      'Round up the usual suspects. - Casablanca, 1942',
      "I'll have what she's having. - When Harry Met Sally, 1989",
      "You know how to whistle, don't you, Steve? You just put your lips together and blow. - To Have and Have Not, 1944",
      "You're gonna need a bigger boat. - Jaws, 1975",
      "Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges! - The Treasure of the Sierra Madre, 1948",
      "I'll be back. - The Terminator, 1984",
      'Today, I consider myself the luckiest man on the face of the earth. - The Pride of the Yankees, 1942',
      'If you build it, he will come. - Field of Dreams, 1989',
      "Mama always said life was like a box of chocolates. You never know what you're gonna get. - Forrest Gump, 1994",
      'We rob banks. - Bonnie and Clyde, 1967',
      'Plastics. - The Graduate, 1967',
      "We'll always have Paris. - Casablanca, 1942",
      "I see dead people. - The Sixth Sense, 1999",
      'Stella! Hey, Stella! - A Streetcar Named Desire, 1951',
      "Oh, Jerry, don't let's ask for the moon. We have the stars. - Now, Voyager, 1942",
      'Shane. Shane. Come back! - Shane, 1953',
      "Well, nobody's perfect. - Some Like It Hot, 1959You might also like: Top 10 Romantic Comedy Movies",
      "It's alive! It's alive! - Frankenstein, 1931Fun fact: The original line was It's alive! It's alive! In the name of God! Now I know what it's like to be God! Censors cut Dr. Frankenstein's full line because it was considered sacrilege.",
      'Houston, we have a problem. - Apollo 13, 1995',
      "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk? - Dirty Harry, 1971",
      'You had me at ‘hello.’ - Jerry Maguire, 1996',
      "One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know. - Animal Crackers, 1930",
      "There's no crying in baseball! - A League of Their Own, 1992You might also like: Top 10 Sports Movies",
      'La-dee-da, la-dee-da. - Annie Hall, 1977',
      "A boy's best friend is his mother. - Psycho, 1960",
      'Greed, for lack of a better word, is good. -  Wall Street, 1987',
      'Keep your friends close, but your enemies closer. - The Godfather Part II, 1974',
      "As God is my witness, I'll never be hungry again. - Gone With the Wind, 1939",
      "Well, here's another nice mess you've gotten me into! - Sons of the Desert, 1933",
      'Say hello to my little friend! - Scarface, 1983',
      'What a dump. - Beyond the Forest, 1949',
      "Mrs. Robinson, you're trying to seduce me. Aren't you? - The Graduate, 1967",
      "Gentlemen, you can't fight in here! This is the War Room! - Dr. Strangelove, 1964",
      'Elementary, my dear Watson. - The Adventures of Sherlock Holmes, 1929',
      'Get your stinking paws off me, you damned dirty ape. - Planet of the Apes, 1968',
      'Of all the gin joints in all the towns in all the world, she walks into mine. - Casablanca, 1942',
      "Here's Johnny! - The Shining, 1980",
      "They're here! - Poltergeist, 1982",
      'Is it safe? - Marathon Man, 1976',
      "Wait a minute, wait a minute. You ain't heard nothin' yet! - The Jazz Singer, 1927",
      'No wire hangers, ever! - Mommie Dearest, 1981',
      'Mother of mercy, is this the end of Rico? -  Little Caesar, 1930',
      "Forget it, Jake, it's Chinatown. - Chinatown, 1974",
      'I have always depended on the kindness of strangers. - A Streetcar Named Desire, 1951',
      'Hasta la vista, baby. - Terminator 2: Judgment Day, 1991',
      'Soylent Green is people! - Soylent Green, 1973',
      'Open the pod bay doors, HAL. - 2001: A Space Odyssey, 1968',
      "Striker: Surely you can't be serious.Rumack: I am serious…and don't call me Shirley. - Airplane!, 1980",
      'Yo, Adrian! - Rocky II, 1979',
      'Hello, gorgeous. - Funny Girl, 1968',
      "Toga! Toga! - National Lampoon's Animal House, 1978",
      'Listen to them. Children of the night. What music they make. - Dracula, 1931',
      "Oh, no, it wasn't the airplanes. It was Beauty killed the Beast. - King Kong, 1933",
      'My precious. - The Lord of the Rings: Two Towers, 2002',
      'Attica! Attica! - Dog Day Afternoon, 1975',
      "Sawyer, you're going out a youngster, but you've got to come back a star! - 42nd Street, 1933",
      "Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go! - On Golden Pond, 1981",
      "Tell 'em to go out there with all they got and win just one for the Gipper. - Knute Rockne All American, 1940",
      "A martini. Shaken, not stirred. - Goldfinger, 1964",
      "Who's on first. - The Naughty Nineties, 1945",
      "Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole! - Caddyshack, 1980",
      'Life is a banquet, and most poor suckers are starving to death! - Auntie Mame, 1958',
      'I feel the need - the need for speed! - Top Gun, 1986',
      'Carpe diem. Seize the day, boys. Make your lives extraordinary. - Dead Poets Society, 1989.',
      'Snap out of it! - Moonstruck, 1987',
      'My mother thanks you. My father thanks you. My sister thanks you. And I thank you. - Yankee Doodle Dandy, 1942',
      'Nobody puts Baby in a corner. - Dirty Dancing, 1987',
      "I'll get you, my pretty, and your little dog, too! - The Wizard of Oz, 1939",
      "I'm king of the world! - Titanic, 1997"],

    funny: ["“I'm sick of following my dreams, man. I'm just going to ask where they're going and hook up with ’em later.—Mitch Hedberg",
    "'Gentlemen, you can't fight in here. This is the war room.”—President Merkin Muffley (Peter Sellers), Dr. Strangelove",
    "'My mother always used to say: The older you get, the better you get, unless you’re a banana.”—Rose (Betty White), The Golden Girls'",
    "'Halloween is the beginning of the holiday shopping season. That’s for women. The beginning of the holiday shopping season for men is Christmas Eve.”—David Letterman'",
    "'Before you criticize someone, you should walk a mile in their shoes. That way when you criticize them, you are a mile away from them and you have their shoes.”—Jack Handey'",
    "'ob: “Looks like you've been missing a lot of work lately.”Peter: “I wouldn't say I've been missing it, Bob.”—Bob (Paul Wilson) and Peter (Ron Livingston), Office Space",
    "'Clothes make the man. Naked people have little or no influence in society.”—Mark Twain'",
    "'Before you marry a person, you should first make them use a computer with slow Internet to see who they really are.”—Will Ferrell'",
    "'I love being married. It's so great to find that one special person you want to annoy for the rest of your life.”—Rita Rudner",
    'ted: New Comedy Movies Release Schedule',
    '“Ned, I would love to stand here and talk with you—but I’m not going to.”—Phil Connors (Bill Murray), Groundhog Day',
    '“When your mother asks, ‘Do you want a piece of advice?’ it is a mere formality. It doesn’t matter if you answer yes or no. You’re going to get it anyway.”—Erma Bombeck',
    '"I want my children to have all the things I couldnt afford. Then I want to move in with them.”—Phyllis Diller',
    '"Never follow anyone else’s path. Unless you’re in the woods and you’re lost and you see a path. Then by all means follow that path.”—Ellen DeGeneres',
    '“Insomnia sharpens your math skills because you spend all night calculating how much sleep you’ll get if you’re able to ‘fall asleep right now.’”—Anonymous',
    '“Breaking up is like knocking over a Coke machine. You can’t do it in one push; you got to rock it back and forth a few times, and then it goes over.”—Jerry (Jerry Seinfeld), Seinfeld',
    '“I’m not superstitious, but I am a little stitious.”—Michael Scott (Steve Carrell), The Office',
    '“I walk around like everything’s fine, but deep down, inside my shoe, my sock is sliding off.”—Anonymous',
    '“I havent spoken to my wife in years. I didnt want to interrupt her.”—Rodney Dangerfield"',
    '“I used to sell furniture for a living. The trouble was, it was my own.”—Les Dawson',
    '“There’s nothing wrong with you that an expensive operation can’t prolong.”—Surgeon (Graham Chapman), Monty Python’s Flying Circus',
    '“Someone asked me, if I were stranded on a desert island what book would I bring: ‘How to Build a Boat.’”—Steven Wright',
    'Ted Striker: “Surely you can’t be serious.”Dr. Rumack: “I am serious. And don’t call me Shirley”—Ted Striker (Robert Hays) and Dr. Rumack (Leslie Nielsen), Airplane!',
    'There is no sunrise so beautiful that it is worth waking me up to see it.”―Mindy Kaling,Is Everyone Hanging Out Without Me?',
    '“You know you’ve reached middle age when you’re cautioned to slow down by your doctor, instead of by the police.”—Joan Rivers',
    '“Truth hurts. Maybe not as much as jumping on a bicycle with a seat missing, but it hurts.”—Lt. Frank Drebin (Leslie Nielsen), Naked Gun 2½: The Smell of Fear',
    '“My Mama says that alligators are ornery because they got all them teeth and no toothbrush.”—Bobby Boucher (Adam Sandler), The Waterboy',
    '“I never feel more alone than when I’m trying to put sunscreen on my back.”—Jimmy Kimmel',
    '“Marriage is like an unfunny, tense version of Everybody Loves Raymond, but it doesn’t last 22 minutes. It lasts forever.”—Pete (Paul Rudd), Knocked Up',
    '“Being a mom means never buying the right amount of produce. Either everyone suddenly loves grapes and a week’s worth are eaten in one afternoon, or fruit flies are congregating around my rotting bananas.”—Lessons from the Minivan',
    '“I’m not insane. My mother had me tested.”—Sheldon Cooper (Jim Parsons), The Big Bang Theory',
    'ted: 101 Corny Jokes',
    '“There are only three ages for women in Hollywood: babe, district attorney and Driving Miss Daisy.”—Elise (Goldie Hawn), The First Wives Club',
    'Usher: “Bride or groom?”Wedding guest: “It should be perfectly obvious I’m neither!”—Four Weddings and a Funeral',
    'Stan Fields: “Describe your perfect date.”Cheryl: “That’s a tough one. I’d have to say April 25. Because it’s not too hot and not too cold. All you need is a light jacket.”—Stan Fields (William Shatner) and Cheryl Frasier (Heather Burns), Miss Congeniality',
    '“I saw a study that said speaking in front of a crowd is considered the number one fear of the average person. Number two was death. This means to the average person, if you have to be at a funeral, you would rather be in the casket than doing the eulogy.”—Jerry Seinfeld',
    'Lucy: “Theres just two things keeping me from dancing in that show.”Fred: “Your feet?”—Lucy (Lucille Ball) andFred Mertz(William Frawley),I Love Lucy"',
    '“Common sense is like deodorant. The people who need it most never use it.”—Anonymous',
    'Coach: “How’s a beer sound, Norm?”Norm: “I dont know, I usually finish before they get a word in.”—Coach (Nicholas Colasanto) and Norm (George Wendt), Cheers"',
    '“If I woke up tomorrow with my head sewn to the carpet, I wouldn’t be more surprised.” —Clark Griswold (Chevy Chase), National Lampoon’s Christmas Vacation',
    'There’s nothing simpler than avoiding people you don’t like. Avoiding one’s friends, that’s the real test.”—Dowager Countess Violet Crawley (Maggie Smith), Downton Abbey',
    '“If I’m not back in five minutes, just wait longer.”—Ace Ventura (Jim Carrey), Ace Ventura: Pet Detective',
    'TED: 101 Knock Knock Jokes',
    '“The only thing that separates us from the animals is our ability to accessorize.”—Clairee Belcher (Olivia Dukakis), Steel Magnolias',
    '“I’m at a place in my life when errands are starting to count as going out.”—Anonymous',
    '“A good rule to remember for life is that when it comes to plastic surgery and sushi, never be attracted by a bargain.”—Graham Norton',
    '“I’m not good at the advice. Can I interest you in a sarcastic comment?”—Chandler (Matthew Perry), Friends',
    '“Here’s all you have to know about men and women: Women are crazy, men are stupid. And the main reason women are crazy is that men are stupid.”—George Carlin',
    '“When Im in social situations, I always hold onto my glass. It makes me feel comfortable and secure and I dont have to shake hands.”—Larry (Larry David), Curb Your Enthusiasm"',
    '“As you get older, three things happen. The first is your memory goes, and I can’t remember the other two.”—Sir Norman Wisdom',
    'That’s why New York is so great, though. Everyone you care about can despise you and you can still find a bagel so good, nothing else matters. Who needs love when you’ve got lox? They both stink, but only one tastes good.” —Midge Maisel (Rachel Brosnahan), The Marvelous Mrs. Maisel',
    '“Here’s some advice: At a job interview, tell them you’re willing to give 110 percent. Unless the job is a statistician.”—Adam Gropman',
    'TED: 100 Good Comebacks',
    '“Does it disturb anyone else that ‘The Los Angeles Angels’ baseball team translates directly to ‘The The Angels Angels’?”—Neil DeGrasse Tyson',
    '“I never forget a face—but in your case, I’ll be glad to make an exception.”—Groucho Marx',
    'ted: 200 Funny Jokes',
    '“Here’s something to think about: How come you never see a headline like ‘Psychic Wins Lottery’?”—Jay Leno',
    '“A day without sunshine is like, you know, night.”—Steve Martin',
    '“My therapist told me the way to achieve true inner peace is to finish what I start. So far I’ve finished two bags of M&Ms and a chocolate cake. I feel better already.”—Dave Barry',
    '“Never do anything out of hunger. Not even eating.”—Frank Semyon(Vince Vaughn), True Detective',
    '“What do you mean, he dont eat no meat? Thats okay, thats okay. I make lamb.”—Aunt Voula (Andrea Martin), My Big Fat Greek Wedding"',
    '“You know you’re getting old when you stoop to tie your shoelaces and wonder what else you could do while you’re down there.”—George Burns',
    '“To call you stupid would be an insult to stupid people!”—Wanda (Jamie Lee Curtis), A Fish Called Wanda',
    '“Instead of the mahi mahi, may I just get the one mahi because I’m not that hungry?”—Shelley Darlingson (Anna Faris), The House Bunny',
    '“Accept who you are. Unless you’re a serial killer.”—Ellen DeGeneres',
    'Francois: “Do you know what kind of a bomb it was?”Clouseau: “The exploding kind.”—Francois (André Maranne) and Inspector Clouseau (Peter Sellers), The Pink Panther Strikes Again',
    '“My ability to turn good news into anxiety is rivaled only by my ability to turn anxiety into chin acne.”—Tina Fey, Bossypants',
    '“There is one word that describes people that dont like me: Irrelevant.”—Anonymous"',
    '“Why do they call it rush hour when nothing moves?”—Robin Williams',
    '“I remember it like it was yesterday. Of course, I don’t really remember yesterday all that well.”—Dory (Ellen DeGeneres), Finding Dory',
    '“I don’t have to take this abuse from you; I’ve got hundreds of people dying to abuse me.”—Dr. Peter Venkman (Bill Murray), Ghostbusters',
    'Police officer: “Pull over.”Harry: “No, it’s a cardigan. But thanks for noticing.”—Harry Dunne (Jeff Daniels), Dumb and Dumber',
    '“I grew up with six brothers. Thats how I learned to dance: waiting for the bathroom.”—Bob Hope"',
    '“If we’re going to pay this much for crab, it better sing and dance and introduce us to the Little Mermaid.”—Claire Foster (Tina Fey), Date Night',
    '“I prefer not to think before speaking. I like being as surprised as everyone else by what comes out of my mouth.”—Anonymous',
    'ted: 101 Funny Puns',
    '“Never put off till tomorrow what you can do the day after tomorrow just as well.”—Mark Twain',
    '“Woke up today. It was terrible.”—Grumpy Cat',
    '“Eggs are fantastic for a fitness diet. If you don’t like the taste, just add cocoa, flour, sugar, butter, baking powder and cook at 350 for 30 minutes.”—Anonymous',
    '“I can’t end my messages with Love, Shaq because the B-52s ruined that for me.”—Meme attributed to Shaquille O’Neal',
    '“My husband and I fell in love at first sight. Maybe I should have taken a second look.”—Halley Reed (Mia Farrow), Crimes and Misdemeanors',
    '“Thanksgiving dinners take 18 hours to prepare. They are consumed in 12 minutes. Half-times take 12 minutes. This is not a coincidence.”—Erma Bombeck',
    '“Insanity runs in my family. It practically gallops.”—Mortimer Brewster (Cary Grant), Arsenic and Old Lace',
    '“Why cant you just be happy for me and then go home and talk behind my back later like a normal person?”—Lillian (Maya Rudolph), Bridesmaids"',
    '“Anyone who lives within their means suffers from a lack of imagination.”—Oscar Wilde',
    '“What they could do to make it easier is combine the two, real estate and obituaries: Mr. Klein died today leaving a wife, two children, and a spacious three-bedroom apartment with a wood-burning fireplace.”—Harry (Billy Crystal),When Harry Met Sally',
    '“I like my money where I can see it: hanging in my closet.”—Carrie (Sarah Jessica Parker), Sex and the City',
    '“The worst part of online shopping is having to get up and get your credit card from your purse.”—Anonymous',
    '“People say, ‘But Betty, Facebook is a great way to connect with old friends.’ Well, at my age, if I want to connect with old friends I need a Ouija board.”—Betty White',
    '“My therapist says Im afraid of success. I guess I could understand that, because after all, fulfilling my potential would really cut into my sitting-around time.”—Maria Bamford"',
    '“From the ages of eight to 18, me and my family moved around a lot. Mostly we would just stretch, but occasionally one of us would actually get up to go to the fridge.”—Jarod Kintz',
    '“Money cannot buy health, but Id settle for a diamond-studded wheelchair.”—Dorothy Parker"',
    '“Good parenting means investing in your childs future, which is why I am saving to buy mine a hoverboard someday.”—Lin-Manuel Miranda"',
    '“I love airports because the rules of society don’t apply. Eat a pizza and have a glass of wine at 7 am while in track pants. Nobody cares.”—Anonymous',
    '“Outside of a dog, a book is man’s best friend. Inside of a dog, it’s too dark to read.”—Groucho Marx',
    '“I’m one stomach flu away from my goal weight.”—Emily Charlton (Emily Blunt), The Devil Wears Prada',
    '“My perfect beautiful miracle baby? Never slept. Ever. Never. Twelve years later the memories of those nights, of that sleep deprivation, still make me rock back and forth a little bit. You want to torture someone? Hand them an adorable baby they love who doesn’t sleep.”—Shonda Rimes',
    '“I’d like to have a kid, but I’m not sure I’m ready to spend 10 years of my life constantly asking someone where his shoes are.”—Damien Fahey',
    '“Why yes, I can carry on a conversation made up entirely of movie quotes.”—Anonymous',
    '“I’m sure wherever my Dad is, he’s looking down on us. He’s not dead, just very condescending.”—Jack Whitehall',
    '“I like long walks, especially when they are taken by people who annoy me.”—Noel Coward',
    ' “Trying is the first step toward failure.”—Homer Simpson, The Simpsons'],

    inspirational: ['“All our dreams can come true, if we have the courage to pursue them.” —Walt Disney',
    '“The secret of getting ahead is getting started.” —Mark Twain',
    '“I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life, and that is why I succeed.” —Michael Jordan',
    '“Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.” —Mary Kay Ash',
    '“The best time to plant a tree was 20 years ago. The second best time is now.” ―Chinese Proverb',
    '“Only the paranoid survive.” —Andy Grove',
    '“It’s hard to beat a person who never gives up.” —Babe Ruth',
    '“I wake up every morning and think to myself, ‘How far can I push this company in the next 24 hours.’” —Leah Busque',
    '“If people are doubting how far you can go, go so far that you can’t hear them anymore.” —Michele Ruiz',
    '“We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes―understanding that failure is not the opposite of success, it’s part of success.” ―Arianna Huffington',
    '“Write it. Shoot it. Publish it. Crochet it. Sauté it. Whatever. MAKE.” —Joss Whedon',
    '“You’ve gotta dance like there’s nobody watching, love like you’ll never be hurt, sing like there’s nobody listening, and live like it’s heaven on earth.” —William W. Purkey',
    '“Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.”―Neil Gaiman',
    '“Everything you can imagine is real.”―Pablo Picasso',
    '“When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.” ―Helen Keller',
    '“Do one thing every day that scares you.” ―Eleanor Roosevelt',
    '“It’s no use going back to yesterday, because I was a different person then.” ―Lewis Carroll',
    '“Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.” —Socrates',
    '“Do what you feel in your heart to be right―for you’ll be criticized anyway.” ―Eleanor Roosevelt',
    '“Happiness is not something ready made. It comes from your own actions.” ―Dalai Lama XIV',
    '“Whatever you are, be a good one.” ―Abraham Lincoln',
    '“The same boiling water that softens the potato hardens the egg. It’s what you’re made of. Not the circumstances.” —Unknown',
    '“If we have the attitude that it’s going to be a great day it usually is.” —Catherine Pulsifier',
    '“You can either experience the pain of discipline or the pain of regret. The choice is yours.” —Unknown',
    '“Impossible is just an opinion.” —Paulo Coelho',
    '“Your passion is waiting for your courage to catch up.” —Isabelle Lafleche',
    '“Magic is believing in yourself. If you can make that happen, you can make anything happen.” —Johann Wolfgang Von Goethe',
    '“If something is important enough, even if the odds are stacked against you, you should still do it.” —Elon Musk',
    '“Hold the vision, trust the process.” —Unknown',
    '“Don’t be afraid to give up the good to go for the great.” —John D. Rockefeller',
    '“People who wonder if the glass is half empty or full miss the point. The glass is refillable.” —Unknown',
    '“One day or day one. You decide.” —Unknown',
    '“It’s Monday … time to motivate and make dreams and goals happen. Let’s go!” —Heather Stillufsen',
    '“It was a Monday and they walked on a tightrope to the sun.” ―Marcus Zusak',
    '“Goodbye, blue Monday.” ―Kurt Vonnegut',
    '“So. Monday. We meet again. We will never be friends—but maybe we can move past our mutual enmity toward a more positive partnership.” ―Julio-Alexi Genao',
    '“When life gives you Monday, dip it in glitter and sparkle all day.” —Ella Woodword',
    '“Monday c’est Mon Day.” —Unknown',
    '“All Motivation Mondays need are a little more coffee and a lot more mascara.” —Unknown',
    '“I’m alive, motivated and ready to slay the day #MONSLAY.” —Unknown',
    '“Oh! It’s Friday again. Share the love that was missing during the week. In a worthy moment of peace and bliss.” —S. O’Sade',
    '“Friday sees more smiles than any other day of the workweek!” —Kate Summers',
    '“Every Friday, I like to high five myself for getting through another week on little more than caffeine, willpower, and inappropriate humor.” —Nanea Hoffman',
    '“When you leave work on Friday, leave work. Don’t let technology follow you throughout your weekend (answering text messages and emails). Take a break. You will be more refreshed to begin the workweek if you have had a break.” —Catherine Pulsifer',
    '“Make Friday a day to celebrate work well done that you can be proud of knowing that you just didn’t put in time to the next paycheck.” —Byron Pulsifer',
    '“I challenge you to let every day be a Friday. Permit yourself to be happy every day.” —Joel Osteen',
    '“This Friday, finish your work and be done. Look forward to the weekend and have some fun!” —Kate Summers',
    '“Fridays are the hardest in some ways: you’re so close to freedom.” —Lauren Oliver',
    '“It’s Friday morning, mankind! Good vibe, don’t frown and let the monster see you smile!” —Napz Cherub Pellazo',
    '“Don’t worry about letting the dogs out. It’s Friday! Let them have a great weekend, too.”―Anthony T. Hincks',
    '“No one is to blame for your future situation but yourself. If you want to be successful, then become ‘Successful.’” ―Jaymin Shah',
    '“Things may come to those who wait, but only the things left by those who hustle.” ―Abraham Lincoln',
    '“Everything comes to him who hustles while he waits.” ―Thomas Edison',
    '“Every successful person in the world is a hustler one way or another. We all hustle to get where we need to be. Only a fool would sit around and wait on another man to feed him.” ―K’wan',
    '“Invest in your dreams. Grind now. Shine later.” ―Unknown',
    '“Hustlers don’t sleep, they nap.” ―Unknown',
    '“Greatness only comes before hustle in the dictionary.” ―Ross Simmonds',
    '“Without hustle, talent will only carry you so far.” ―Gary Vaynerchuk',
    '“Work like there is someone working 24 hours a day to take it away from you.” ―Mark Cuban',
    '“Hustle in silence and let your success make the noise.” ―Unknown',
    '“We are what we repeatedly do. Excellence, then, is not an act, but a habit.” ―Aristotle',
    '“If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.” ―Sheryl Sandberg',
    '“I always did something I was a little not ready to do. I think that’s how you grow. When there’s that moment of ‘Wow, I’m not really sure I can do this,’ and you push through those moments, that’s when you have a breakthrough.” ―Marissa Mayer',
    '“If you hear a voice within you say, ‘You cannot paint,’ then by all means paint, and that voice will be silenced.” ―Vincent Van Gogh',
    '“How wonderful it is that nobody need wait a single moment before starting to improve the world.” ―Anne Frank',
    '“Some people want it to happen, some wish it would happen, others make it happen.” ―Michael Jordan',
    '“Great things are done by a series of small things brought together.” ―Vincent Van Gogh',
    '“If you hire people just because they can do a job, they’ll work for your money. But if you hire people who believe what you believe, they’ll work for you with blood and sweat and tears.” ―Simon Sinek',
    '“Very often, a change of self is needed more than a change of scene.’ ―A.C. Benson',
    '“Leaders can let you fail and yet not let you be a failure.” ―Stanley McChrystal',
    '“It’s not the load that breaks you down, it’s the way you carry it.” ―Lou Holtz',
    '“The hard days are what make you stronger.” ―Aly Raisman',
    '“If you believe it’ll work out, you’ll see opportunities. If you don’t believe it’ll work out, you’ll see obstacles.” ―Wayne Dyer',
    '“Keep your eyes on the stars, and your feet on the ground.” ―Theodore Roosevelt',
    '“You can waste your lives drawing lines. Or you can live your life crossing them.” ―Shonda Rhimes',
    '“You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.” ―George Lorimer',
    '“I now tried a new hypothesis: It was possible that I was more in charge of my happiness than I was allowing myself to be.” ―Michelle Obama',
    '“In a gentle way, you can shake the world.” ―Mahatma Gandhi',
    '“If opportunity doesn’t knock, build a door.” ―Kurt Cobain',
    '“Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.” ―Roy T. Bennett',
    '“Work hard in silence, let your success be the noise.” ―Frank Ocean',
    '“Don’t say you don’t have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo da Vinci, Thomas Jefferson, and Albert Einstein.” ―H. Jackson Brown Jr.',
    '“Hard work beats talent when talent doesn’t work hard.” ―Tim Notke',
    '“If everything seems to be under control, you’re not going fast enough.” ―Mario Andretti',
    '“Opportunity is missed by most people because it is dressed in overalls and looks like work.” ―Thomas Edison',
    '“The only difference between ordinary and extraordinary is that little extra.” ―Jimmy Johnson',
    '“The best way to appreciate your job is to imagine yourself without one.” ―Oscar Wilde',
    '“Unsuccessful people make their decisions based on their current situations. Successful people make their decisions based on where they want to be.” ―Benjamin Hardy',
    '“Never stop doing your best just because someone doesn’t give you credit.” ―Kamari aka Lyrikal',
    '“Work hard for what you want because it won’t come to you without a fight. You have to be strong and courageous and know that you can do anything you put your mind to. If somebody puts you down or criticizes you, just keep on believing in yourself and turn it into something positive.” ―Leah LaBelle',
    '“The miracle is not that we do this work, but that we are happy to do it.” ―Mother Teresa',
    '“Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.” ―Earl Nightingale',
    '“If you work on something a little bit every day, you end up with something that is massive.” ―Kenneth Goldsmith',
    '“The big secret in life is that there is no secret. Whatever your goal, you can get there if you’re willing to work.” ―Oprah Winfrey',
    '“If you cannot do great things, do small things in a great way.” ―Napoleon Hill',
    '“Never allow a person to tell you no who doesn’t have the power to say yes.” ―Eleanor Roosevelt',
    '“At any given moment you have the power to say: this is not how the story is going to end.” ―Unknown',
    '“Amateus sit around and wait for inspiration. The rest of us just get up and go to work.” ―Stephen King',
    '“Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it.” ―Steve Jobs',
    '“Nothing will work unless you do.” ―Maya Angelou'],

    life_lesson: ['“Yesterday is not ours to recover, but tomorrow is ours to win or lose.”– Lyndon B. Johnson',
    '“Why let go of yesterday? Because yesterday has already let go of you.” – Steve Maraboli',
    '“Only the dead have seen the end of war.” ― Plato',
    '“You’ve gotta know when it’s time to turn the page.” – Tori Amos',
    '“Though nobody can go back and make a new beginning… Anyone can start over and make a new ending.” ― Chico Xavier',
    '“Every new beginning comes from some other beginning’s end.” – Seneca',
    '“I do a good job of staying positive and just moving on.” – Katie Taylor',
    '“Letting go does not mean you stop caring. It means you stop trying to force others to.”– Mandy Hale',
    '“You only struggle because you’re ready to grow but aren’t willing to let go.” – Drew Gerald',
    '“We are products of our past, but we don’t have to be prisoners of it.” ― Rick Warren',
    '“Forgive yourself for your faults and your mistakes and move on.” – Les Brown',
    '“Some of us think holding on makes us strong, but sometimes it is letting go.”– Herman Hesse',
    '“You don’t learn to walk by following rules. You learn by doing, and by falling over.” ― Richard Branson',
    '“Courage is the power to let go of the familiar.”– Raymond Lindquist',
    '“In three words I can sum up everything I’ve learned about life: it goes on.” – Robert Frost',
    '“Every day is a new day, and you’ll never be able to find happiness if you don’t move on.” – Carrie Underwood',
    '“Anything you can’t control is teaching you how to let go.” – Jackson Kiddard',
    '“You can’t move forward if you’re still hanging on.” – Sue Fitzmaurice',
    '“Nothing in the universe can stop you from letting go and starting over.”– Guy Finley',
    '“If there’s a single lesson that life teaches us, it’s that wishing doesn’t make it so.” ― Lev Grossman',
    '“A man who wakes up and finds himself a success hasn’t been asleep.” – Dave Thomas',
    '“Be yourself — everyone else is already taken.” – Oscar Wilde',
    '“Fear is not a good teacher. The lessons of fear are quickly forgotten.” – Mary Catherine Bateson',
    '“Sooner or later we’ve all got to let go of our past.”– Dan Brown',
    '“It’s not the mistake that matters, it’s how you interpret the lesson.” – Michelle C. Ustaszeski',
    '“I am learning to love the sound of my feet walking away from things not meant for me.” – A.G.',
    '“Your past does not equal your future.”– Anthony Robbins',
    '“Sometimes the hardest part isn’t letting go but rather learning to start over.” ― Nicole Sobon',
    '“You don’t have to let that one thing be the thing that defines you.” ― Jojo Moyes',
    '“Every defeat, every heartbreak, every loss, contains its own seed, its own lesson on how to improve your performance the next time.” – Og Mandino',
    '“It’s time to say goodbye, but I think goodbyes are sad and I’d much rather say hello. Hello to a new adventure.” – Ernie Harwell',
    '“The past is a place of reference, not a place of residence; the past is a place of learning, not a place of living.” ― Roy T. Bennett',
    '“Courage is the most important of all the virtues because without courage, you can’t practice any other virtue consistently.” ― Maya Angelou',
    '“Most people claim that they feel like they’re trapped in a rat race, without an exit. While we can all feel this way from time to time, it’s important to know that there is a way out.” – Debeena Harris',
    '“It happens to everyone as they grow up. You find out who you are and what you want, and then you realize that people you’ve known forever don’t see things the way you do. So you keep the wonderful memories, but find yourself moving on.” ― Nicholas Sparks',
    '“A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them.” – John C. Maxwell',
    '“We all make them, the difference is what we do after we make the mistake, how we see the mistake – a learning experience or a failure.” – Catherine Pulsifer',
    '“You make mistakes. Mistakes don’t make you.” – Maxwell Maltz',
    '“There is no sense in punishing your future for the mistakes of your past. Forgive yourself, grow from it, and then let it go.” – Melanie Koulouris',
    '“The great courageous act that we must all do, is to have the courage to step out of our history and past so that we can live our dreams.” ― Oprah Winfrey',
    '“We must be willing to let go of the life we’ve planned, so as to have the life that is waiting for us.”– Joseph Campbell',
    '“Over the years I’ve come to realize that mistakes are just lessons, life lessons almost like school. Once you’ve learned a lesson in class, you move on to the next lesson because now you know it. Well mistakes are exactly the same.” – Rashard Royster',
    '“One of the most courageous decisions you’ll ever make is to finally let go of what is hurting your heart and soul.” – B. Nicole',
    '“Happiness is not the absence of problems, it’s the ability to deal with them.” ― Steve Maraboli',
    '“My greatest life lessons have not come from any achievements I have attained but rather from the failures, heartaches, and setbacks that I have experienced.” – Dr. Marshall HenningtonIf you’re enjoying these quotes, you’ll love our collection of experience quotes that will inspire you to live a fulfilled life.',
    '“When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.”– Alexander Graham Bell',
    '“There comes a time in your life when you have to choose to turn the page, write another book or simply close it.” ― Shannon L. Alder',
    '“A very wise man once told me that you can’t look back-you just have to put the past behind you, and find something better in your future.” ― Jodi Picoult',
    '“I’ve been burdened with blame trapped in the past for too long, I’m moving on” ― Rascal Flatts',
    '“To be successful, you must act big, think big and talk big.” – Aristotle Onassis',
    '“Life is 10% what happens to you and 90% how you react.” –Tony Robbins',
    '“If you can dream it, you can do it.” – Walt Disney',
    '“Luck is what happens when preparation meets opportunity.” – SenecaIf you’re enjoying these quotes, you’ll love our collection of Seneca quotes that will help you in all facets of your life.',
    '“Letting go isn’t a one-time thing, it’s something you have to do every day, over and over again.” – Dawson’s Creek',
    '“Letting go doesn’t mean that you don’t care about someone anymore. It’s just realizing that the only person you really have control over is yourself.” ― Deborah Reber',
    '“Behind every adversity is an opportunity. If you lament over the adversity, you will miss the opportunity.” – Ajaero Tony Martins',
    '“I don’t dwell on the things that are too late to fix, but I do my best to get life’s lessons and put them into action.” – Les Brown',
    '“Never be ashamed! There’s some who will hold it against you, but they are not worth bothering with.” – J.K. Rowling',
    '“Think of each failure, each heartache, and each loss in your life as a lesson in courage and resilience.” – Kate Anderson',
    '“Accept yourself, love yourself, and keep moving forward. If you want to fly, you have to give up what weighs you down.” – Roy T. Bennett',
    '“Make improvements, not excuses. Seek respect, not attention.” – Roy T. Bennett',
    '“Pursue what catches your heart, not what catches your eyes.” – Roy T. Bennett',
    '“Let the improvement of yourself keep you so busy that you have no time to criticize others." – Roy T. Bennett',
    '“In this life, when you deny someone an apology, you will remember it at time you beg forgiveness.” – Toba Beta',
    '“It’s clearly easier to get the snake out of the sack than it is to shove it back.” – Mary Morris',
    '“Knowing when to forgive yourself and correct yourself is a blessing.” – Angel Moreira',
    '“When something happens and it causes us pain, the pain is there to teach us a lesson. It is not so that we feel pain for the sake of pain.” – Cave Man',
    '“Be humble to those who praise you, pleasant to those who honor you, kind to those who cherish you, good to those who love you, and generous to those who adore you.” – Matshona Dhliwayo',
    '“We cannot change the past. We can only take action in the present and, therefore, change the future.” – Ken Poirot',
    '“Take chances, make mistakes. That’s how you grow. Pain nourishes your courage. You have to fail in order to practice being brave.” ―Mary Tyler Moore',
    '“There are no passengers on spaceship earth. We are all crew.” ―Marshall McLuhan',
    '“Avoid doing the same you always do or the day will fill like an incoming tide.” – Allan Jenkins',
    '“Life is available only in the present. That is why we should walk in such a way that every step can bring us to the here and the now.” – Thich Nhat Hanh',
    '“In every success story, you will find someone who has made a courageous decision.” –Peter F. Drucker',
    '“Forget the past.” – Nelson Mandela',
    '“Time doesn’t heal emotional pain, you need to learn how to let go.” – Roy T. Bennett',
    '“The first step towards getting somewhere is to decide that you are not going to stay where you are.” – J.P. Morgan',
    '“Look at life through the windshield, not the rear-view mirror.” – Byrd Baggett',
    '“We can not become what we need to by remaining what we are.” – Oprah Winfrey',
    '“People can be more forgiving than you can imagine. But you have to forgive yourself. Let go of what’s bitter and move on.” – Bill Cosby',
    '“Take the first step in faith. You don’t have to see the whole staircase, just take the first step.” – Martin Luther King Jr.',
    '“Moving on, is a simple thing, what it leaves behind is hard.” – Dave Mustaine',
    '“You must make a decision that you are going to move on. It won’t happen automatically. You will have to rise up and say, ’I don’t care how hard this is, I don’t care how disappointed I am, I’m not going to let this get the best of me. I’m moving on with my life.” – Joel Osteen']
  };
   
    
  
  const generateQuote= () =>{
      let topic = "", 
          quote = "";

      options.forEach(element => {
          if(element.checked){
              topic = characters[element.id];
              quote =  topic[Math.floor(Math.random() * topic.length)];
          }

      });

      quoteInput.value = quote;
    }


  const copyPassword = () =>{
      navigator.clipboard.writeText(quoteInput.value);
  }

  generate.addEventListener('click', generateQuote);
  copy.addEventListener('click', copyPassword);


});
